num1 = input('Ingrese un numero que quiera sumar ')
num1 = int(num1)
num2 = input('Ingrese un segundo numero que desee sumar ')
num2 = int(num2)
suma = (num1 + num2)
print('La suma de sus numeros es ', suma)
